# Generated by Django 2.1.7 on 2019-10-01 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_datasets_projects_submissions_user_proj_auth_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data_Demo',
            new_name='Data_Old',
        ),
        migrations.RenameModel(
            old_name='Projects_Demo',
            new_name='Projects_Old',
        ),
        migrations.RenameModel(
            old_name='Submissions_Demo',
            new_name='Submissions_Old',
        ),
        migrations.RenameModel(
            old_name='Submissions_SA_Demo',
            new_name='Submissions_SA_Old',
        ),
        migrations.RenameModel(
            old_name='User_Demo',
            new_name='User_Old',
        ),
    ]
