# Generated by Django 2.1.7 on 2019-10-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20191001_0619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Data_Old',
        ),
        migrations.DeleteModel(
            name='Projects_Old',
        ),
        migrations.DeleteModel(
            name='Submissions_Old',
        ),
        migrations.DeleteModel(
            name='Submissions_SA_Old',
        ),
        migrations.DeleteModel(
            name='User_Old',
        ),
    ]
