version: '2'

services:
  website:
    image: raniac/neuro-learn-website:dev
    restart: on-failure
    network_mode: host
    volumes:
      - /opt/nlw/log:/nlw/log
    container_name: website-dev

  service-api:
    image: raniac/neuro-learn-service:api
    restart: on-failure
    network_mode: host
    volumes:
      - /opt/nls/api/log:/nls-api/log
    container_name: service-api

  service-ml:
    image: raniac/neuro-learn-service:ml
    restart: on-failure
    network_mode: host
    volumes:
      - /opt/nls/ml/log:/nls-ml/log
    container_name: service-ml

  # service-sgn:
  #   image: raniac/neuro-learn-service:sgn
  #   # restart: on-failure
  #   network_mode: host
  #   volumes:
  #     - /opt/nls/sgn/log:/nls-sgn/log
  #     - /opt/nls/sgn/models:/nls-sgn/models
  #   container_name: service-sgn