version: '2'

services:
  website:
    image: raniac/neuro-learn-website:dev
    # restart: on-failure
    network_mode: host
    container_name: website-dev

  service-commons:
    image: raniac/neuro-learn-service:commons
    # restart: on-failure
    network_mode: host
    volumes:
      - /opt/nls/commons/log:/nls-commons/log
    container_name: service-commons

  service-ml:
    image: raniac/neuro-learn-service:ml
    # restart: on-failure
    network_mode: host
    volumes:
      - /opt/nls/ml/log:/nls-ml/log
    container_name: service-ml

  service-sgn:
    image: raniac/neuro-learn-service:sgn
    # restart: on-failure
    network_mode: host
    volumes:
      - /opt/nls/sgn/log:/nls-sgn/log
      - /opt/nls/sgn/models:/nls-sgn/models
    container_name: service-sgn